### ISSUE TITLE
cifar10 dataset train

### ISSUE THREAD

**Issue by world2025** [TreezzZ/ITQ_PyTorch#1]
hello, thanks for your codes. the codes donnot use for cifar 10? can you tell me how to use cifar 10 ?thx

**Comment by TreezzZ** [comment]
> hello, thanks for your codes. the codes donnot use for cifar 10? can you tell me how to use cifar 10 ?thx

I have already updated codes of ITQ and supported nus-wide, imagenet datasets. Please use `git pull` command to get the latest codes. :)
